Repository cse110-sp21-group18/Bullet-Journal-App, pull requests merged in 2021-06, with the labels that each got.

#104 Test pull request template
  index.html
Labels: documentation

#105 Small css user improvements
  components/logList.js
  components/settingsModal.js
  css/color_themes.css
  css/navbar.css
  css/sidebar_stylesheet.css
Labels: CSS, enhancement

#106 Add favicon
  Files/Icons/favicon-1.ico
  index.html
Labels: Enhancement, HTML

#107 Read Me Update
  README.md
Labels: Documentation, Enhancement

#108 Interfaced Key with Bullet Entries + Comments
  components/bulletEntries.js
  components/key-button.js
  components/logList.js
  components/settingsModal.js
  index.html
  scripts/indexdb.js
  scripts/router.js
  style.css
Labels: Enhancement, Feature, Javascript

#112 Jsdoc comments
  components/bulletEntries.js
  components/datepicker.js
  components/key-button.js
  components/logList.js
  components/settingsModal.js
  scripts/indexdb.js
  scripts/navigation.js
  scripts/router.js
Labels: Documentation

#113 More comments
  components/bulletEntries.js
  components/datepicker.js
  components/key-button.js
  components/logList.js
  components/settingsModal.js
  scripts/navigation.js
Labels: Documentation, Enhancement

#114 Onboarding doc
  Onboard.md
  README.md
Labels: Documentation, Enhancement

#115 Onboarding doc
  onboarding/ESLint-Prettier-Local-Install-Use-Guide.md
  onboarding/images/ESLint_JSON.jpg
  onboarding/images/Prettier_JSON.jpg
  onboarding/onboard.md
Labels: Documentation, Enhancement

#120 History bug fix and testing
  __test__/history.test.js
  components/logList.js
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov.info
  scripts/router.js
Labels: Bug, Testing

#122 Added a comment to index.html
  index.html
Labels: Documentation, HTML
